#!/bin/bash
set -Eeo pipefail

iface=$(basename "$0" | sed 's/^if_//g')



if [[ $1 == "config" ]];
then
  echo "graph_order down up"
  echo "graph_title ${iface} traffic"
  echo "graph_args --base 1000"
  echo "graph_vlabel bits in (-) / out (+) per ${graph_period}"
  echo "graph_category network"
  echo "down.label received"
  echo "down.type COUNTER"
  echo "down.graph no"
  echo "down.min 0"
  echo "down.cdef down,8,*"
  echo "up.label bps"
  echo "up.type COUNTER"
  echo "up.negative down"
  echo "up.min 0"
  echo "up.cdef up,8,*"
  exit 0
fi

up=$(cat /sys/class/net/${iface}/statistics/tx_bytes)
down=$(cat /sys/class/net/${iface}/statistics/rx_bytes)
echo "up.value ${up}"
echo "down.value ${down}"

